"""AI-text detection endpoint.

Detects whether supplied text was likely generated by an AI. Uses the Gemini
backend when ``GEMINI_API_KEY`` is configured, otherwise falls back to the
offline heuristic detector (bigram perplexity proxy + stylometric signals).
"""

from __future__ import annotations

import sys
from pathlib import Path

from flask import Blueprint, jsonify, request

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from ml.ai_text_detector import detect_ai_generated  # noqa: E402

from ..config import Config  # noqa: E402
from ..utils.errors import ValidationError  # noqa: E402

bp = Blueprint("ai_detector", __name__, url_prefix="/api")

MIN_AI_TEXT_CHARS = 20


@bp.post("/detect-ai-text")
def detect_ai_text():
    data = request.get_json(silent=True) or {}
    text = str(data.get("text") or "").strip()
    if len(text) < MIN_AI_TEXT_CHARS:
        raise ValidationError(
            f"Text is too short for AI-text detection ({len(text)} characters). "
            f"Please provide at least {MIN_AI_TEXT_CHARS} characters."
        )
    if len(text) > Config.MAX_ARTICLE_LENGTH:
        raise ValidationError(
            f"Text is too long ({len(text)} characters). "
            f"Maximum allowed is {Config.MAX_ARTICLE_LENGTH}."
        )
    return jsonify(detect_ai_generated(text))
